name: wasix-test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0-dev.2571+01081cc8e

      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@v3.1

      - name: Build for WASM
        run: zig build -Dtarget=wasm32-wasi

      - name: Run tests
        run: wasmer run --enable-all --net --enable-async-threads --http-client --verbose zig-out/bin/wasix-test.wasm
